version: '3'

services:
  mysql: 
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - openmerce-mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

  nginx-fs:
    image: ghcr.io/tus1688/go-nginx-fs:main
    container_name: nginx-fs
    restart: always
    environment:
      AUTHORIZATION: ${AUTHORIZATION}
    ports:
      - ${NGINX_FS_PORT}:5000
    volumes:
      - openmerce-nginx-fs-data:/usr/share/nginx/html

volumes:
  openmerce-mysql:
    external: true
  redis:
  openmerce-nginx-fs-data:
    external: true
