version: '3'

services:
  mysql: 
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - openmerce-network
    ports:
      - ${DB_PORT}:3306
    volumes:
      - openmerce-mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - openmerce-network
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

  nginx-fs:
    image: ghcr.io/tus1688/go-nginx-fs:main
    container_name: nginx-fs
    restart: always
    environment:
      AUTHORIZATION: ${AUTHORIZATION}
    ports:
      - ${NGINX_FS_PORT}:5000
    volumes:
      - openmerce-nginx-fs-data:/usr/share/nginx/html

  freight:
    image: freightservice:local
    container_name: freight
    restart: always
    environment:
      AUTHORIZATION_HEADER: ${AUTHORIZATION_FREIGHT}
      DB_NAME: ${DB_NAME_FREIGHT}
      DB_USER: ${DB_USER_FREIGHT}
      DB_PASS: ${DB_PASS_FREIGHT}
      DB_HOST: ${DB_HOST_FREIGHT}
      DB_PORT: ${DB_PORT_FREIGHT}
      REDIS_HOST: ${REDIS_HOST_FREIGHT}
      REDIS_PORT: ${REDIS_PORT_FREIGHT}
      GIN_MODE: release
    networks:
      - openmerce-network
    ports:
      - ${FREIGHT_PORT}:5000
    depends_on:
      - mysql
      - redis

volumes:
  openmerce-mysql:
    external: true
  redis:
  openmerce-nginx-fs-data:
    external: true

networks:
  openmerce-network: