name: remote ssh command

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd deployment
            docker compose pull
            docker compose down
            docker compose up -d